language: objective-c

osx_image: xcode7

before_install:
- gem install cocoapods
- pod install --project-directory=Example

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail && xcodebuild test -workspace Example/PhotoSliderDemo.xcworkspace -scheme PhotoSliderDemo -destination-timeout 1 -sdk iphonesimulator -configuration Debug -destination 'name=iPhone 6'
- pod lib lint --quick
